### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by gardner** [cobudget/cobudget#185]
Steps to reproduce:
```
docker-compose run cobudget-api bundle exec rake db:migrate && \
docker-compose run cobudget-api bundle exec rake db:setup && \
docker-compose run cobudget-api bundle exec rspec


Failures:

  1) BucketsController#archive behavior live bucket sends refund notification emails to funders
     Failure/Error: expect(recipients).to match_array(contributor_emails)
     
       expected collection contained:  ["annetta@stanton.info", "mya.considine@barton.com"]
       actual collection contained:    []
       the missing elements were:      ["annetta@stanton.info", "mya.considine@barton.com"]
     # ./spec/controllers/buckets_controller_spec.rb:358:in `block (5 levels) in <top (required)>'

  2) BucketsController#archive behavior live bucket, one member is archived before cancel sends refund notification emails to funders and admins
     Failure/Error: expect(recipients).to match_array(expected_emails)
     
       expected collection contained:  ["rylee@weinat.info", "sabina_runolfsdottir@muller.org", "sibyl@klocko.co"]
       actual collection contained:    []
       the missing elements were:      ["rylee@weinat.info", "sabina_runolfsdottir@muller.org", "sibyl@klocko.co"]
     # ./spec/controllers/buckets_controller_spec.rb:415:in `block (5 levels) in <top (required)>'

  3) BucketsController#archive behavior funded bucket sends refund notification emails to funders
     Failure/Error: expect(recipients).to match_array(contributor_emails)
     
       expected collection contained:  ["rubie@barrows.com", "will.pagac@luettgendaniel.info"]
       actual collection contained:    []
       the missing elements were:      ["rubie@barrows.com", "will.pagac@luettgendaniel.info"]
     # ./spec/controllers/buckets_controller_spec.rb:462:in `block (5 levels) in <top (required)>'

  4) BucketsController#archive behavior funded, archived bucket sends refund notification emails to funders
     Failure/Error: expect(recipients).to match_array(contributor_emails)
     
       expected collection contained:  ["albina@mertzwyman.biz", "joelle_hane@bailey.co"]
       actual collection contained:    []
       the missing elements were:      ["albina@mertzwyman.biz", "joelle_hane@bailey.co"]
     # ./spec/controllers/buckets_controller_spec.rb:506:in `block (5 levels) in <top (required)>'

  5) MembershipsController#invite current_user signed in current_user is admin of user's group member to be invited is not yet a confirmed user of cobudget sends invite email with link to 'confirm-account-page' to specified user
     Failure/Error: expect(sent_emails.length).to eq(4)
     
       expected: 4
            got: 0
     
       (compared using ==)
     # ./spec/controllers/memberships_controller_spec.rb:256:in `block (6 levels) in <top (required)>'

  6) MembershipsController#invite current_user signed in current_user is admin of user's group member to be invited is already a confirmed user of cobudget sends invite email with link to 'group-page' to specified user
     Failure/Error: expect(sent_emails.length).to eq(1)
     
       expected: 1
            got: 0
     
       (compared using ==)
     # ./spec/controllers/memberships_controller_spec.rb:283:in `block (6 levels) in <top (required)>'

  7) UsersController#create specified email does not yet exist in DB sends email to user with link to confirm account page containing confirmation_token
     Failure/Error: expect(@sent_email.to).to eq([@new_user.email])
     
     NoMethodError:
       undefined method `to' for nil:NilClass
     # ./spec/controllers/users_controller_spec.rb:31:in `block (4 levels) in <top (required)>'

  8) UsersController#request_password_reset user has already set up their account sends them a reset password email with link to reset_password page containing their reset_password_token
     Failure/Error: expect(@sent_email.to).to eq([user.email])
     
     NoMethodError:
       undefined method `to' for nil:NilClass
     # ./spec/controllers/users_controller_spec.rb:216:in `block (4 levels) in <top (required)>'

  9) UsersController#request_password_reset user has not set up their account yet sends them a reset password email with link to confirm_account page containing their confirmation_token
     Failure/Error: expect(@sent_email.to).to eq([user.email])
     
     NoMethodError:
       undefined method `to' for nil:NilClass
     # ./spec/controllers/users_controller_spec.rb:236:in `block (4 levels) in <top (required)>'

  10) DeliverRecentActivityEmails #to_email_notification_subscribers! sends recent_personal_activity_emails to users with active memberships, who are subscribed_to_email_notifications, and who have had personal_activity in their groups in the last hour
      Failure/Error: expect(email_recipients).to include(user_with_recent_activity.email)
        expected [] to include "jeanie@luettgen.info"
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:42:in `block (4 levels) in <top (required)>'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:147:in `travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:121:in `send_travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:51:in `freeze'
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:38:in `block (3 levels) in <top (required)>'

  11) DeliverRecentActivityEmails #to_daily_digest_subscribers! sends activity digest emails to users whose local time is 6am, with email_digest_delivery_frequency set to daily, containing recent_activity from the day previous, if it exists
      Failure/Error: expect(email_recipients).to include(parisian_user_with_activity_in_the_past_24_hours.email)
        expected [] to include "margaret@hegmann.net"
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:108:in `block (4 levels) in <top (required)>'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:147:in `travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:121:in `send_travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:51:in `freeze'
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:97:in `block (3 levels) in <top (required)>'

  12) DeliverRecentActivityEmails #to_weekly_digest_subscribers! sends activity digest emails to users whose local time is monday 6am, with email_digest_delivery_frequency set to weekly, containing recent_activity from the week previous, if it exists
      Failure/Error: expect(email_recipients).to include(parisian_user_with_activity_in_the_past_week.email)
        expected [] to include "deborah@wehnerkirlin.com"
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:173:in `block (4 levels) in <top (required)>'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:147:in `travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:121:in `send_travel'
      # /usr/local/bundle/gems/timecop-0.8.1/lib/timecop/timecop.rb:51:in `freeze'
      # ./spec/extras/deliver_recent_activity_emails_spec.rb:162:in `block (3 levels) in <top (required)>'

  13) Group membership cleanup by moving funds from archived member to group account sends mails to admins
      Failure/Error: expect(recipients).to match_array(admin_emails)
      
        expected collection contained:  ["crawford@bailey.name", "rick@sporer.net"]
        actual collection contained:    []
        the missing elements were:      ["crawford@bailey.name", "rick@sporer.net"]
      # ./spec/models/group_spec.rb:114:in `block (4 levels) in <top (required)>'

  14) MembershipService #archive_membership(membership: ) archives member's funding buckets, and refunds all its contributors, and sends email notifications to refunded contributors, except author
      Failure/Error: expect(sent_emails.length).to eq(2)
      
        expected: 2
             got: 0
      
        (compared using ==)
      # ./spec/services/membership_service_spec.rb:77:in `block (3 levels) in <top (required)>'

Finished in 2 minutes 5.4 seconds (files took 2.52 seconds to load)
267 examples, 14 failures, 2 pending
```

**Comment by gardner** [comment]
These tests were failing due to a misconfiguration with mailcatcher.
