### ISSUE TITLE
[BUG] yarn crowdin:upload not working anymore

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#851]
I run `yarn crowdin:upload` to upload newly extracted strings but I get this

```
% yarn crowdin:upload
yarn run v1.22.19
$ ../scripts/crowdin.sh upload

> dreams-ui@0.1.0 crowdin
> crowdin upload

/home/me/prj/plato/cobudget/ui/node_modules/@crowdin/cli/jdeploy-bundle/jdeploy.js:30
    const fetch = require('node-fetch')
                  ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/me/prj/plato/cobudget/ui/node_modules/node-fetch/src/index.js from /home/me/prj/plato/cobudget/ui/node_modules/@crowdin/cli/jdeploy-bundle/jdeploy.js not supported.
Instead change the require of index.js in /home/me/prj/plato/cobudget/ui/node_modules/@crowdin/cli/jdeploy-bundle/jdeploy.js to a dynamic import() which is available in all CommonJS modules.
    at njreWrap (/home/me/prj/plato/cobudget/ui/node_modules/@crowdin/cli/jdeploy-bundle/jdeploy.js:30:19)
    at Object.<anonymous> (/home/me/prj/plato/cobudget/ui/node_modules/@crowdin/cli/jdeploy-bundle/jdeploy.js:330:14) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.9.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Might be that I'm on node 18 now. I tried updating `@crowdin/cli` to 3.8.1 but that didn't help.

**Comment by Powersource** [comment]
If we really need to we can probably upload en.json manually

**Comment by alinauroz** [comment]
node-fetch version 2.x would fix the issue. Can you try deleting node_modules folder and then re-installing the modules

**Comment by aerugo** [comment]
@Powersource - could you check if the issue is resolved?

**Comment by Powersource** [comment]
seems fixed!
